---
- name: "Install Docker on Ubuntu"
  hosts: all
  become: true
  tasks:
    - name: "Update apt cache"
      apt:
        update_cache: true
      ignore_errors: true

    - name: "Task #1: Install Docker requirements"
      apt:
        name:
          - curl
          - ca-certificates
          - apt-transport-https
          - software-properties-common
        state: present

    - name: "Task #2: Add Docker GPG key"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: "Task #3: Add Docker apt repo"
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: "Task #4: Update apt cache"
      apt:
        update_cache: yes

    - name: "Task #5: Install Docker (docker-ce)"
      ansible.builtin.apt:
        name: docker-ce
        state: present

    - name: "Check Docker service status"
      command: systemctl status docker
      register: docker_status

    - name: "Display Docker service status"
      debug:
        var: docker_status.stdout_lines
