name: Github Actions Playground

on:
  push:
    paths:
      - "**.py"

jobs:
  Checkout_Code: # As per Slides: creating artifact as the first action.
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.timestamp.outputs.time }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Timestamp
        id: timestamp
        run: echo "::set-output name=time::$(date +%s)"

      - name: Archive Code
        uses: actions/upload-artifact@v3
        with:
          name: repo-code-${{ steps.timestamp.outputs.time }}
          path: .

  Linting: # I'm just checking the data, not enforcing it to be correct for the overall pipeline to finish successfully.
    needs: Checkout_Code
    if: contains(github.event.head_commit.message, '/lint') # Check if commit message contains /lint
    runs-on: ubuntu-latest
    steps:
      - name: Download Code
        uses: actions/download-artifact@v3
        with:
          name: repo-code-${{ needs.Checkout_Code.outputs.timestamp }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install black flake8

      - name: Run Linter
        uses: wearerequired/lint-action@v2
        with:
          black: true
          flake8: true

  Exploring:
    needs: Checkout_Code
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello, World!"

      - name: Trigger Info
        run: echo "This action was triggered by a ${{ github.event_name }}"

  Publish:
    needs: [Checkout_Code, Exploring]
    runs-on: ubuntu-latest
    steps:
      - name: Download Code
        uses: actions/download-artifact@v2
        with:
          name: repo-code-${{ needs.Checkout_Code.outputs.timestamp }}

      - name: Publish Start
        run: echo "Publishing the project"

      - name: Publish Completion
        run: echo "Publish complete"
