name: Github Actions Demo
on: [push]
jobs: 
  Exploring:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello, World!"
      - name: Trigger Info
        run: echo "This action was triggered by a ${{ github.event_name }}"
  
  Building:
    runs-on: ubuntu-latest
    steps:
      - name: Build Start
        run: echo "Building the project ${{ secrets.TEST_SECRET }}"
      - name: Build Completion
        run: echo "Build complete ${{ vars.TESTVARIABLE }} "
